# Generated by Django 3.1.7 on 2021-04-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='photos/%Y%m%d')),
            ],
        ),
    ]
