# Generated by Django 3.1.7 on 2021-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
