# Generated by Django 2.2.13 on 2020-10-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200930_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('background_color', models.CharField(default='#209cee', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='api.Label')),
                ('precursor_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precursor', to='api.Label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='api.Project')),
            ],
            options={
                'unique_together': {('project', 'text')},
            },
        ),
    ]
