# Generated by Django 2.2.13 on 2020-10-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='follow_label',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='precursor_label',
        ),
        migrations.AddField(
            model_name='relationship',
            name='prefix_key',
            field=models.CharField(blank=True, choices=[('ctrl', 'ctrl'), ('shift', 'shift'), ('ctrl shift', 'ctrl shift')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='suffix_key',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('g', 'g'), ('h', 'h'), ('i', 'i'), ('j', 'j'), ('k', 'k'), ('l', 'l'), ('m', 'm'), ('n', 'n'), ('o', 'o'), ('p', 'p'), ('q', 'q'), ('r', 'r'), ('s', 's'), ('t', 't'), ('u', 'u'), ('v', 'v'), ('w', 'w'), ('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='RelationshipAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precursor_label_offset', models.IntegerField()),
                ('follow_label_offset', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_annotations', to='api.Document')),
                ('follow_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_label', to='api.Label')),
                ('precursor_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precursor_label', to='api.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user', 'precursor_label', 'follow_label', 'precursor_label_offset', 'follow_label_offset')},
            },
        ),
    ]
